### ISSUE TITLE
TypeError: selections[key][group] is undefined

### ISSUE THREAD

**Issue by jameelmoses** [mattkeys/ACF-Conditional-Taxonomy-Rules#1]
I get this error whenever I try to edit a field in a field group.

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/16327472/32703388-0cabcbb2-c7c3-11e7-8455-7276e1570607.png">

WP Version: 4.8.3
ACF PRO Version: 5.6.5

**Comment by bookwyrm** [comment]
I encountered the same issue and addressed it with the attached code update. Submitting a PR has been on my todo list for a couple weeks now.

[0001-Check-for-valid-group-before-setting-value.txt](https://github.com/mattkeys/ACF-Conditional-Taxonomy-Rules/files/1467556/0001-Check-for-valid-group-before-setting-value.txt)

**Comment by jameelmoses** [comment]
Made a PR for you @bookwyrm. Thanks!

@mattkeys can we get this reviewed and merged in please?

**Comment by jameelmoses** [comment]
Thanks, @mattkeys! Field is working beautifully now 💯

**Comment by mattkeys** [comment]
Hey guys, thank you for being proactive and finding a resolution to this issue. I've merged a slightly tweaked version of the pull request in.

I have a newer version of this plugin that is somewhat of a complete rewrite. I've run into a number of edge cases with v1 that cause issues. Particularly when mixing multiple types of conditionals on a single field. The newer version is a bit more robust and has a simpler and easier to follow codebase. However I need to finish up some more testing before releasing.

I am hoping to get back to it in the coming weeks, but if it takes too long maybe I will put what I have out there in a sub branch for anyone else to pick up on if there is interest.
