### ISSUE TITLE
Add support for Github Updater Plugin/Add Plugin URI to link to github

### ISSUE THREAD

**Issue by yosefeliezrie** [mattkeys/ACF-Conditional-Taxonomy-Rules#16]
Thanks for this awesome little plugin. its Helped me on several projects. I just wish Elliot and ACF would add this to the core of ACF Pro. Just two small suggestions to make it easier on users.

**Github Updater Support**

It great if you added support for the[ Github Updater WordPress plugin.](https://github.com/afragen/github-updater).

> This plugin was designed to simply update any GitHub hosted WordPress plugin or theme. Your plugin or theme must contain a header in the style.css header or in the plugin's header denoting the location on GitHub. The format is as follows.

```
GitHub Plugin URI: mattkeys/ACF-Conditional-Taxonomy-Rules
GitHub Plugin URI: https://github.com/mattkeys/ACF-Conditional-Taxonomy-Rules
```

**[Add Plugin URL headers](https://developer.wordpress.org/plugins/plugin-basics/header-requirements/)**

Can you please add `Plugin URL` headers 

`Plugin URI: https://github.com/mattkeys/ACF-Conditional-Taxonomy-Rule`

**This will mean your plugin headers will now be**
```
/**
Plugin Name: ACF Conditional Taxonomy Rules
Plugin URI: https://github.com/mattkeys/ACF-Conditional-Taxonomy-Rule
GitHub Plugin URI: https://github.com/mattkeys/ACF-Conditional-Taxonomy-Rules
Description: Allow conditional rules to use 'taxonomy' field types
Version: 3.0.1
Author: mattkeys
Author URI: http://mattkeys.me
License: GPL2
License URI: https://www.gnu.org/licenses/gpl-2.0.html
*/
```

**Comment by mattkeys** [comment]
Done. I do not use this plugin so someone will need to report back to me if there are any issues.
