### ISSUE TITLE
Doesn't seem to work with ACF 5.6.6

### ISSUE THREAD

**Issue by UnionDesign** [mattkeys/ACF-Conditional-Taxonomy-Rules#4]
TypeError: undefined is not an object (evaluating 'acf.conditional_logic.items[ key ]')

**Comment by mattkeys** [comment]
Looks like 5.6.6 introduced some updates to the way conditional logic is handled which broke compatibility with this plugin. I've introduced some fixes along with some other reworking of this plugin in a new version (2.0.0). I just launched it, let me know if it works for you.
