### ISSUE TITLE
WP Metaboxes won't collapse

### ISSUE THREAD

**Issue by UnionDesign** [mattkeys/ACF-Conditional-Taxonomy-Rules#6]
When plugin is active WordPress Metaboxes can no longer open/close. Disabling ACF Pro fixes the issue but when both plugins are active the issue exists. So some kind of JS conflict between ACF Pro and ACF Conditional Tax 2.0.0?

Test Config:
- WordPress 4.9.2
- ACF Pro 5.6.7
- ACF Conditional Tax 2.0.0
- Twenty Seventeen Theme
- Safari 11.0.2
- Mac OS 10.13.2
- No other plugins active

**Comment by mattkeys** [comment]
It sounds like there is a JS error, can you check your console and report back with the error?

**Comment by brentbarkley** [comment]
I'm having same issue--same stats as above. Error is:

`TypeError: acf.conditional_logic is undefined

	renderField
https://denovo-us.com/wp-content/plugins/acf-conditional-taxonomy/includes/input_conditional_taxonomy.js:131:8
renderFields/<
https://denovo-us.com/wp-content/plugins/acf-conditional-taxonomy/includes/input_conditional_taxonomy.js:107:5
each
https://denovo-us.com/wp-admin/load-scripts.php:2:2879
each
https://denovo-us.com/wp-admin/load-scripts.php:2:844
renderFields
https://denovo-us.com/wp-content/plugins/acf-conditional-taxonomy/includes/input_conditional_taxonomy.js:105:4
render
https://denovo-us.com/wp-content/plugins/acf-conditional-taxonomy/includes/input_conditional_taxonomy.js:37:4
l/<
https://denovo-us.com/wp-content/plugins/advanced-custom-fields-pro/assets/js/acf-input.min.js:4:13820
u
https://denovo-us.com/wp-content/plugins/advanced-custom-fields-pro/assets/js/acf-input.min.js:1:12792
i
https://denovo-us.com/wp-content/plugins/advanced-custom-fields-pro/assets/js/acf-input.min.js:1:11806
c.doAction
https://denovo-us.com/wp-content/plugins/advanced-custom-fields-pro/assets/js/acf-input.min.js:1:4766
<anonymous>
https://denovo-us.com/wp-content/plugins/advanced-custom-fields-pro/assets/js/acf-input.min.js:1:11160
i
https://denovo-us.com/wp-admin/load-scripts.php:2:27444
fireWith
https://denovo-us.com/wp-admin/load-scripts.php:2:28213
ready
https://denovo-us.com/wp-admin/load-scripts.php:2:30004
K
https://denovo-us.com/wp-admin/load-scripts.php:2:30366
`
