### ISSUE TITLE
Not working in ACF Pro 5.6.10 WP 4.9.5

### ISSUE THREAD

**Issue by nszumowski** [mattkeys/ACF-Conditional-Taxonomy-Rules#9]
This doesn't seem to be working for me anymore, using ACF Pro 5.6.10 and WP 4.9.5. I can no longer select a taxonomy in Conditional Logic, and when editing a post the conditional fields no longer show.

I've tried disabling all other plugins and using a core theme and tested in a clean WP install as well.

Anything else I can do to test?

Thanks for any help!

**Comment by diavollo03** [comment]
Hey,

Please see this https://github.com/mattkeys/ACF-Conditional-Taxonomy-Rules/compare/master...diavollo03:patch-1 - it worked for me.

Cheers

**Comment by nszumowski** [comment]
yes, thanks dude!

**Comment by mattkeys** [comment]
Thanks for the fix diavollo03. Also FYI it seems that ACF 5.7 is going to include this conditional taxonomy fields (and all sorts of other conditional functionality). So it should not be much longer before this plugin is no longer needed.

**Comment by mattkeys** [comment]
Interesting, I checked the changelog and 5.7 says it got major JS and conditional rework. However when testing just now the conditional choices I see when trying to use a taxonomy field in a conditional are pretty weird. It offers: "has a value", "has no value", or some stuff about a value less/greater than, which I am not sure how that helps given taxonomy terms are typically strings.

I am not sure if Elliot is still working on this or not. This plugin could probably be updated to work with the new conditional JS, and I may have to if it isn't updated officially soon as I use this with a client site.

With that said I am pretty buried right now so I am not sure when I will have time to revisit.

**Comment by brentbarkley** [comment]
No worries--definitely wasn't expecting you to update. And you're right--on first look I thought I didn't see taxonomies, but there they are...and as you noted, I don't understand how the controls are of any use for a taxonomy string. Regardless, I appreciate your quick responses.

**Comment by bookwyrm** [comment]
5.7 does include support for conditional fields based on taxonomy term but the implementation is kinda weird. There's a support post about it which explains how to make it work: https://support.advancedcustomfields.com/forums/topic/conditional-logic-using-taxonomies/

**Comment by mattkeys** [comment]
I was wondering if that greater than/less than stuff would work with the term IDs. Good to know. a bit clunky to use but nice that it is native in the plugin.
